#!/usr/bin/env python3
"""AssetForge Stack 4 command-line runner."""
from __future__ import annotations
import argparse
from pathlib import Path

from dotenv import load_dotenv

from assetforge.core.config_loader import ConfigLoader
from assetforge.core.pipeline import Pipeline
from assetforge.core.provider_settings import (
    PRODUCTION_PROVIDERS,
    PROVIDER_LABELS,
    ProviderSettings,
    ProviderSettingsStore,
    provider_from_menu_choice,
    provider_menu_text,
)
from assetforge.core.state import AssetForgeState
from assetforge.engine.gs001_input_validation import GS001InputValidation
from assetforge.engine.gs002_character_lock import GS002CharacterLock
from assetforge.engine.gs003_camera_setup import GS003CameraSetup
from assetforge.engine.gs004_generation import GS004Generation
from assetforge.engine.gs005_qa import GS005QA
from assetforge.engine.gs006_export import GS006Export
from assetforge.engine.gs007_package import GS007Package
from assetforge.engine.gs008_report import GS008Report
from assetforge.providers import MockProvider, OpenAIImageConfig, OpenAIImageProvider
from assetforge.workflow import (
    CanaryRunner,
    CodexBridge,
    IterationManifest,
    IterationManifestLoader,
    ManifestAwaitingApprovalError,
    ManifestCatalog,
    ProductionWorkflowGuard,
    WorkflowAction,
    WorkflowCheckpointStore,
)


def success_message(stack_revision: str, provider: str) -> str:
    return f"{stack_revision} completed successfully with provider: {provider}."

def main() -> int:
    parser = argparse.ArgumentParser(description="Run AssetForge Stack 3 workflows")
    parser.add_argument("--project-root", type=Path, default=Path("projects/Soldier_AK47"))
    parser.add_argument("--config-root", type=Path, default=Path("configs/core"))
    manifest_group = parser.add_mutually_exclusive_group()
    manifest_group.add_argument(
        "--manifest",
        type=Path,
        help="Iteration manifest YAML. Defaults to configs/core/Manifest.yaml.",
    )
    manifest_group.add_argument(
        "--next",
        action="store_true",
        help="Run the next approved manifest from the local catalog.",
    )
    parser.add_argument(
        "--manifest-root",
        type=Path,
        default=Path("configs/iterations"),
        help="Directory containing approved iteration manifests.",
    )
    parser.add_argument(
        "--provider",
        choices=("mock", "openai", "closeai", "codex"),
        help="Temporary provider override. Otherwise the saved setting is used.",
    )
    provider_switch = parser.add_mutually_exclusive_group()
    provider_switch.add_argument(
        "--provider-menu",
        action="store_true",
        help="Open the interactive 1/2/3 provider switcher.",
    )
    provider_switch.add_argument(
        "--set-provider",
        choices=PRODUCTION_PROVIDERS,
        help="Save the active application provider.",
    )
    provider_switch.add_argument(
        "--show-provider",
        action="store_true",
        help="Show the active application provider and exit.",
    )
    codex_permission = parser.add_mutually_exclusive_group()
    codex_permission.add_argument(
        "--authorize-codex-generation",
        action="store_true",
        help="Persist permission to upload configured references to Codex generation.",
    )
    codex_permission.add_argument(
        "--revoke-codex-generation",
        action="store_true",
        help="Revoke persisted Codex reference-upload permission.",
    )
    parser.add_argument(
        "--provider-settings",
        type=Path,
        default=Path("configs/local/Provider.yaml"),
        help="Non-secret persistent provider setting.",
    )
    parser.add_argument(
        "--canary",
        action="store_true",
        help="Generate exactly one view for human review without advancing workflow state.",
    )
    parser.add_argument(
        "--canary-camera",
        default="CAM01",
        help="Camera ID for the one-view canary (default: CAM01).",
    )
    parser.add_argument(
        "--probe-provider",
        action="store_true",
        help="List image-capable models without generating an image.",
    )
    parser.add_argument(
        "--codex-import",
        type=Path,
        help="Import a transparent PNG generated by Codex into the prepared canary job.",
    )
    parser.add_argument(
        "--approve-canary",
        action="store_true",
        help="Record explicit human approval of the current Codex canary.",
    )
    parser.add_argument(
        "--approved-by",
        default="user",
        help="Reviewer identity stored with --approve-canary.",
    )
    parser.add_argument(
        "--prepare-codex-batch",
        action="store_true",
        help="Prepare remaining camera jobs after canary approval without generating images.",
    )
    parser.add_argument(
        "--evaluate-codex-batch",
        action="store_true",
        help="Run structural QA and create a contact sheet after all camera imports.",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Explicitly rebuild an iteration already recorded as complete.",
    )
    parser.add_argument(
        "--status",
        action="store_true",
        help="Show the persisted workflow checkpoint without running the pipeline.",
    )
    parser.add_argument(
        "--plan",
        action="store_true",
        help="Show all ten iteration slots and local manifest readiness.",
    )
    args = parser.parse_args()
    load_dotenv(dotenv_path=Path(".env"), override=False)

    provider_store = ProviderSettingsStore(args.provider_settings)
    try:
        provider_settings = provider_store.load()
        if args.provider_menu:
            print(provider_menu_text(provider_settings.active_provider))
            selected = provider_from_menu_choice(input("Choose provider [1/2/3]: "))
            provider_settings = ProviderSettings(
                selected,
                provider_settings.codex_reference_upload_authorized,
            )
            provider_store.save(provider_settings)
            print(f"ACTIVE PROVIDER: {PROVIDER_LABELS[selected]} ({selected}).")
            return 0
        if args.set_provider:
            provider_settings = ProviderSettings(
                args.set_provider,
                provider_settings.codex_reference_upload_authorized,
            )
            provider_store.save(provider_settings)
            print(
                f"ACTIVE PROVIDER: {PROVIDER_LABELS[args.set_provider]} "
                f"({args.set_provider})."
            )
            return 0
        if args.authorize_codex_generation or args.revoke_codex_generation:
            authorized = bool(args.authorize_codex_generation)
            provider_settings = ProviderSettings(
                provider_settings.active_provider,
                authorized,
            )
            provider_store.save(provider_settings)
            state = "AUTHORIZED" if authorized else "REVOKED"
            print(f"CODEX REFERENCE UPLOAD: {state}.")
            return 0
        if args.show_provider:
            active = provider_settings.active_provider
            print(f"ACTIVE PROVIDER: {PROVIDER_LABELS[active]} ({active}).")
            state = (
                "AUTHORIZED"
                if provider_settings.codex_reference_upload_authorized
                else "NOT AUTHORIZED"
            )
            print(f"CODEX REFERENCE UPLOAD: {state}.")
            return 0
    except (EOFError, OSError, ValueError, TypeError) as error:
        print(f"ERROR: Provider switch failed: {error}")
        return 1
    provider_name = args.provider or provider_settings.active_provider

    configs = ConfigLoader(args.config_root).load_all()
    checkpoint_store = WorkflowCheckpointStore()
    try:
        checkpoint = checkpoint_store.load(args.project_root)
    except (OSError, ValueError, KeyError) as error:
        print(f"ERROR: Invalid workflow checkpoint: {error}")
        return 1
    try:
        catalog = ManifestCatalog.discover(
            args.config_root / "Manifest.yaml",
            args.manifest_root,
        )
        if args.next:
            selected_manifest = catalog.next_entry(checkpoint).manifest
            configs["Manifest.yaml"] = dict(selected_manifest.data)
        elif args.manifest:
            selected_manifest = IterationManifestLoader().load(args.manifest)
            configs["Manifest.yaml"] = dict(selected_manifest.data)
        else:
            selected_manifest = IterationManifest.from_mapping(configs["Manifest.yaml"])
    except ManifestAwaitingApprovalError as error:
        print(f"BLOCKED: {error}")
        return 1
    except (OSError, ValueError, KeyError, TypeError) as error:
        print(f"ERROR: Invalid iteration manifest: {error}")
        return 1
    manifest_iteration = selected_manifest.iteration
    if args.status:
        if checkpoint is None:
            print("Workflow has not started.")
        else:
            print(
                f"Iteration {checkpoint.completed_iteration:02d}: {checkpoint.status}; "
                f"mode={checkpoint.mode}; progress={checkpoint.project_progress:.0%}; "
                f"next={checkpoint.next_iteration if checkpoint.next_iteration else 'none'}; "
                f"stack={checkpoint.stack_revision}; provider={provider_name}."
            )
        return 0
    if args.plan:
        print("ID  STATUS             NAME")
        for line in catalog.describe(checkpoint):
            print(line)
        return 0

    if provider_name == "codex":
        codex_actions = sum(
            bool(value)
            for value in (
                args.approve_canary,
                args.prepare_codex_batch,
                args.evaluate_codex_batch,
            )
        )
        if codex_actions > 1:
            print("ERROR: Choose one Codex batch action at a time.")
            return 1
        if not args.canary and codex_actions == 0:
            print("BLOCKED: Codex Bridge currently supports one-view canary mode only.")
            return 1
        try:
            bridge = CodexBridge()
            if args.approve_canary:
                approved = bridge.approve_canary(
                    project_root=args.project_root,
                    iteration=manifest_iteration,
                    camera_id=args.canary_camera,
                    approved_by=args.approved_by,
                )
                print(
                    f"{approved.status}: {args.canary_camera} canary approved. "
                    f"Review record: {approved.report}. Workflow state was not advanced."
                )
                return 0
            if args.prepare_codex_batch:
                batch = bridge.prepare_batch(
                    project_root=args.project_root,
                    iteration=manifest_iteration,
                    configs=configs,
                    approved_camera_id=args.canary_camera,
                )
                print(
                    f"{batch.status}: prepared {len(batch.jobs)} remaining camera jobs. "
                    f"Batch plan: {batch.plan}. No generation was started."
                )
                return 0
            if args.evaluate_codex_batch:
                camera_ids = tuple(configs["CameraLibrary.yaml"]["cameras"])
                qa = bridge.evaluate_batch(
                    project_root=args.project_root,
                    iteration=manifest_iteration,
                    camera_ids=camera_ids,
                )
                print(
                    f"STRUCTURAL QA {qa.status}: report={qa.report}; "
                    f"contact_sheet={qa.contact_sheet}; human review is still required."
                )
                return 0
            job = bridge.prepare(
                project_root=args.project_root,
                iteration=manifest_iteration,
                configs=configs,
                camera_id=args.canary_camera,
            )
            if args.codex_import:
                if args.canary_camera == "CAM01":
                    imported = bridge.import_result(
                        job=job,
                        source_image=args.codex_import,
                        iteration=manifest_iteration,
                        camera_id=args.canary_camera,
                    )
                else:
                    imported = bridge.import_batch_result(
                        job=job,
                        source_image=args.codex_import,
                        project_root=args.project_root,
                        iteration=manifest_iteration,
                        camera_id=args.canary_camera,
                    )
                print(
                    f"{imported.status}: imported {imported.asset}. "
                    f"Review record: {imported.report}. Workflow state was not advanced."
                )
            else:
                print(
                    f"AWAITING_CODEX: request prepared at {job.request}. "
                    f"Expected output: {job.output}. Workflow state was not advanced."
                )
        except (OSError, ValueError, KeyError, TypeError) as error:
            print(f"ERROR: Codex Bridge failed: {error}")
            return 1
        return 0

    if provider_name in {"openai", "closeai"} and args.probe_provider:
        try:
            config = (
                OpenAIImageConfig.from_env()
                if provider_name == "openai"
                else OpenAIImageConfig.from_closeai_env()
            )
            models = OpenAIImageProvider(config).probe_image_models()
        except (OSError, RuntimeError, ValueError) as error:
            print(f"ERROR: Provider probe failed: {error}")
            return 1
        print("Image models: " + (", ".join(models) if models else "none reported"))
        return 0
    if provider_name in {"openai", "closeai"} and not args.canary:
        print(
            "BLOCKED: paid full-batch generation is disabled until a canary image "
            f"has passed human review. Run with --provider {provider_name} --canary."
        )
        return 1
    if args.canary:
        try:
            if provider_name in {"openai", "closeai"}:
                config = (
                    OpenAIImageConfig.from_env()
                    if provider_name == "openai"
                    else OpenAIImageConfig.from_closeai_env()
                )
                provider = OpenAIImageProvider(config)
            else:
                provider = MockProvider()
            canary = CanaryRunner().run(
                project_root=args.project_root,
                iteration=manifest_iteration,
                configs=configs,
                provider=provider,
                camera_id=args.canary_camera,
            )
        except (OSError, RuntimeError, ValueError) as error:
            print(f"ERROR: Canary generation failed: {error}")
            return 1
        print(
            f"{canary.status}: generated one {args.canary_camera} image at {canary.asset}. "
            f"Review record: {canary.report}. Workflow state was not advanced."
        )
        return 0

    decision = ProductionWorkflowGuard().evaluate(
        manifest_iteration,
        checkpoint,
        force=args.force,
    )
    print(decision.message)
    if decision.action == WorkflowAction.ALREADY_COMPLETE:
        return 0
    if decision.action == WorkflowAction.BLOCKED:
        return 1
    state = AssetForgeState(
        project_name=configs["MPI.yaml"].get("project", {}).get("name", "Character_Project"),
        iteration=manifest_iteration,
        progress=0.10,
        configs=configs,
        metadata={
            "project_root": str(args.project_root),
            "provider": MockProvider(),
            "stack_revision": "Stack_04_Rev00",
        },
    )
    result = Pipeline(
        [
            GS001InputValidation(),
            GS002CharacterLock(),
            GS003CameraSetup(),
            GS004Generation(),
            GS005QA(),
            GS006Export(),
            GS007Package(),
            GS008Report(),
        ]
    ).run(state)
    for line in result.logs:
        print(line)
    if result.errors:
        for error in result.errors:
            print(f"ERROR: {error}")
        return 1
    print(success_message(result.metadata["stack_revision"], provider_name))
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
